In [ ]:
import pandas as pd


df = pd.read_csv("")

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

df['qesc'] = scaler.fit_transform(df['qesc'])


cond = df['qesc']>0.5

print(len(cond))

In [8]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch2/members.csv")

print(df.head(3))

#df.sort_values('views', ascending = False , inplace = True)
# inplace = 정렬된 데이터로 변경
df.sort_values('views',ascending = False,inplace = True)

min_value = df['views'][:10].min()

print(min_value)
#iloc - 데이터를 쓸떄 write이때 사용한다.
df.iloc[:10,-1] = min_value

print(df.head(10))


cond = df['age']>=80

result = df[cond]['views'].mean()


print(round(result , 2))

     id   age city    f1  f2    f3    f4         f5  subscribed   views
0  id01   2.0   서울   NaN   0  gold  ENFJ  91.297791  2021-07-16  6820.0
1  id02   9.0   서울  70.0   1   NaN  ENFJ  60.339826  2021-05-12  2534.0
2  id03  27.0   서울  61.0   1  gold  ISTJ  17.252986  2021-03-16  7312.0
9690.0
       id   age city    f1  f2    f3    f4         f5  subscribed   views
5    id06  22.0   서울  57.0   0   vip  INTP  20.129444  2021-09-12  9690.0
56   id56  59.0   대구   NaN   1   vip  ESTJ  73.586397  2021-04-05  9690.0
83   id83  73.0   경기  50.0   1   vip  ENTP  80.138280  2021-09-26  9690.0
32   id32  25.0   부산  64.0   0   vip  ISFJ  13.049921  2021-05-24  9690.0
10  id100  47.0   경기  53.0   0   vip  ESFP  33.308999  2021-02-21  9690.0
9    id10  95.0   서울  74.0   1  gold  ISFP  98.429899  2021-04-03  9690.0
49   id49  75.0   대구  88.0   0  gold  INTP  37.113739  2021-03-31  9690.0
36   id36  68.0   부산  77.0   1  gold  INTP  13.049921  2021-07-20  9690.0
46   id46  93.0   대구   NaN   0  gold  ESTJ  67.886373  2021-05-23  9690.0
21   id21  90.0   부산   NaN   1  gold  ISFP  29.269869  2021-05-03  9690.0
5674.04

In [ ]:
# 데이터 불러오기
import pandas as pd
# X_test = pd.read_csv("X_test.csv")
# X_train = pd.read_csv("X_train.csv")
# y_train = pd.read_csv("y_train.csv")
X_test = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch2/X_test.csv")
X_train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch2/X_train.csv")
y_train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch2/y_train.csv")

# 데이터 합치기
df = pd.concat([X_train , y_train ['Reached.on.Time_Y.N']],axis = 1)


# print(X_train.head(3))
# print(X_train.info())
# print(X_train.describe(include = 'object'))

# X_train = pd.get_dummies(X_train)
# X_test = pd.get_dummies(X_test)

      ID Warehouse_block Mode_of_Shipment  Customer_care_calls  \
0   8440               B             Ship                    4
1  10849               D             Ship                    3
2   9478               B             Ship                    4

   Customer_rating  Cost_of_the_Product  Prior_purchases Product_importance  \
0                1                  284                4                low
1                2                  201                4             medium
2                4                  181                3             medium

  Gender  Discount_offered  Weight_in_gms
0      F                 4           4795
1      M                10           5565
2      F                 9           4425
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8799 entries, 0 to 8798
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   8799 non-null   int64
 1   Warehouse_block      8799 non-null   object
 2   Mode_of_Shipment     8799 non-null   object
 3   Customer_care_calls  8799 non-null   int64
 4   Customer_rating      8799 non-null   int64
 5   Cost_of_the_Product  8799 non-null   int64
 6   Prior_purchases      8799 non-null   int64
 7   Product_importance   8799 non-null   object
 8   Gender               8799 non-null   object
 9   Discount_offered     8799 non-null   int64
 10  Weight_in_gms        8799 non-null   int64
dtypes: int64(7), object(4)
memory usage: 756.3+ KB
None
       Warehouse_block Mode_of_Shipment Product_importance Gender
count             8799             8799               8799   8799
unique               5                3                  3      2
top                  F             Ship                low      F
freq              2929             5972               4225   4450

In [ ]:
# 데이터 불러오기
import pandas as pd
# train = pd.read_csv("train.csv")
# test = pd.read_csv("test.csv")
train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch3/train.csv")
test = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch3/test.csv")

print(train.head(3))
print(train.info())

# Employment GraduateOrNot

from sklearn.preprocessing import LabelEncoder


le = LabelEncoder()

train.shape , test.shape

# train = le.fit_transform(train)
# test = le.transform(test)

train = pd.get_dummies(train)
test = pd.get_dummies(test)
target = train.pop('TravelInsurance')

from sklearn.model_selection import train_test_split

x_train, x_val , y_train , y_val = train_test_split(train, target , test_size = 0.2 , random_state = 0)

from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(random_state = 0)

model.fit(x_train, y_train)
pred = model.predict(x_val)


from sklearn.metrics import f1_score
f1score = f1_score(pred, y_val)

print(f1score)


#1. 0.77 (random + onehot encoding)


result = pd.DataFrame({'pred':pred})
result.to_csv("submit.csv")

   Unnamed: 0  Age               Employment Type GraduateOrNot  AnnualIncome  \
0         888   28  Private Sector/Self Employed           Yes       1250000
1        1308   31  Private Sector/Self Employed           Yes       1250000
2         151   29  Private Sector/Self Employed           Yes       1200000

   FamilyMembers  ChronicDiseases FrequentFlyer EverTravelledAbroad  \
0              6                1            No                  No
1              7                1            No                  No
2              7                0            No                  No

   TravelInsurance
0                0
1                0
2                1
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1490 entries, 0 to 1489
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           1490 non-null   int64
 1   Age                  1490 non-null   int64
 2   Employment Type      1490 non-null   object
 3   GraduateOrNot        1490 non-null   object
 4   AnnualIncome         1490 non-null   int64
 5   FamilyMembers        1490 non-null   int64
 6   ChronicDiseases      1490 non-null   int64
 7   FrequentFlyer        1490 non-null   object
 8   EverTravelledAbroad  1490 non-null   object
 9   TravelInsurance      1490 non-null   int64
dtypes: int64(6), object(4)
memory usage: 116.5+ KB
None
0.7448979591836735

In [ ]:
import pandas as pd
# df = pd.DataFrame({
#     "항암약":[4,4,3,4,1,4,1,4,1,4,4,2,1,4,2,3,2,4,4,4]
#     })
# print(df.head(3))

# cnt = (sum(df['항암약'] == 4))

# ratio = cnt/ len(df)

# print(ratio)

# # print(df['항암약'].value_counts(normalize = True))

# #카이제곱 - 관찰 빈도 기대 빈도 필요함

# obs_count = df['항암약'].value_counts().sort_index().to_list()
# print(obs_count)


# #기대 빈도
# prob = [0.1,0.05,0.15,0.7]
# exp_count = [x*len(df) for x in prob]

# from scipy.stats import chisquare

# print(chisquare(f_obs =obs_count , f_exp = exp_count ))

df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch6/data6-3-2.csv")

#다중선형회귀

print(df.head(3))

formula = 'temperature~ solar + wind +o3'

from statsmodels.formula.api import ols

model = ols(formula, data = df).fit()


summary = model.summary()
# print(summary)

# print(model.params['o3'])


# print(model.pvalues['wind'])

new_data = pd.DataFrame({'solar':[100], 'wind' : [5], 'o3':[30]})

pred = model.predict(new_data)

    solar  wind     o3  temperature
0   89.14  6.28  33.52         23.0
1  109.97  1.04  27.01         20.7
2  102.83  6.42  41.00         20.5
                            OLS Regression Results
==============================================================================
Dep. Variable:            temperature   R-squared:                       0.044
Model:                            OLS   Adj. R-squared:                  0.014
Method:                 Least Squares   F-statistic:                     1.464
Date:                Wed, 26 Nov 2025   Prob (F-statistic):              0.229
Time:                        11:57:20   Log-Likelihood:                -195.45
No. Observations:                 100   AIC:                             398.9
Df Residuals:                      96   BIC:                             409.3
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     19.0507      1.994      9.555      0.000      15.093      23.008
solar          0.0039      0.015      0.251      0.802      -0.027       0.035
wind          -0.0252      0.090     -0.280      0.780      -0.204       0.153
o3             0.0749      0.036      2.079      0.040       0.003       0.146
==============================================================================
Omnibus:                        0.654   Durbin-Watson:                   2.328
Prob(Omnibus):                  0.721   Jarque-Bera (JB):                0.672
Skew:                           0.187   Prob(JB):                        0.715
Kurtosis:                       2.855   Cond. No.                     1.20e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.2e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
0.07493854378136597
0.7797177202071699

In [7]:
import pandas as pd
# df = pd.read_csv("clam.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch7/clam.csv")

# from statsmodels.formula.api import logit 
# import numpy as np
train = df[:210]
test = df[210:]

# print(train.shape) 
# print(test.shape)


# formula = 'gender ~ weight '

# model = logit(formula , data = train).fit()

# odds_ratio = np.exp(model.params['weight'])
# print(round(odds_ratio,4))

from statsmodels.formula.api import logit
import numpy as np
formula = 'gender ~ age + length + diameter + height + weight'
# formula 독립변수 설정시 +로 지정 fomula = 'gender ~ age + length'

model = logit(formula , data = train).fit()

print(round(-2*model.llf,2))
#잔차 이탈도 - 로그우도에 -2 곱한것 -2*model.llf


#error rate = 1- accuracy

from sklearn.metrics import accuracy_score
formula = 'gender ~ weight'
model = logit(formula, data = train).fit()
target = test.pop('gender')
pred= model.predict(test)
pred = (pred>0.5).astype(int)

accuracy = accuracy_score(target, pred)
error_rate = 1-accuracy
print(round(error_rate,3))

Optimization terminated successfully.
         Current function value: 0.683173
         Iterations 4
286.93
Optimization terminated successfully.
         Current function value: 0.690045
         Iterations 4
0.478

In [16]:
import pandas as pd
# df = pd.read_csv("data6-3-2.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch6/data6-3-2.csv")
from statsmodels.formula.api import ols

# 선형 회귀 - ols 

#1 다중 선형 회귀 모델 구축 및 o3 회귀 계소

print(df.head(3))

formula = 'temperature ~ solar + wind + o3'

model = ols(formula , data = df).fit()

#print(model.summary())

#0.0749

#print(model.params['o3'])


#2 solar 와 o3 가 고정된 상태에서 wind 세기가 증가함에 따라 temperature가 감소 wind에대한 coef
# 그냥 회귀계수를 어렵게 말한거임

print(model.pvalues['wind'])
#pvalues params 는 () 를 치치 않음 [] 그냥 이렇게 마무리


new_data = pd.DataFrame({'solar':[100],
                         'wind':[5],
                         'o3': [30]})

pred = model.predict(new_data)
print(pred)

    solar  wind     o3  temperature
0   89.14  6.28  33.52         23.0
1  109.97  1.04  27.01         20.7
2  102.83  6.42  41.00         20.5
0.7797177202071699
0    21.56163
dtype: float64

In [21]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch8/churn.csv")
# formula = "Churn ~ AccountWeeks + ContractRenewal + DataPlan + DataUsage + CustServCalls + DayMins + DayCalls + MonthlyCharge + OverageFee + RoamMins"

# from statsmodels.formula.api import logit
# model = logit(formula,  data = df).fit()
# print(model.summary())
# sum(model.pvalues[1:]>0.05)

# formula = "Churn ~ DataUsage + DayMins "
# model = logit(formula , data =df).fit()
# print(model.summary())
# round(sum(model.params,3))
# import numpy as np
# coef = model.params['DataUsage']
# round(np.exp(coef*5),3)


import pandas as pd
from statsmodels.formula.api import ols
# df = pd.read_csv("piq.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch8/piq.csv")
print(df.head(3))

formula = 'PIQ ~ Brain + Height + Weight'

model = ols(formula, data = df).fit()

print(model.summary())

# 1. 2.343

#2 

print(round(model.rsquared,2))

#3 새로운 데이터의 PIQ

new_data = pd.DataFrame({'Brain': [90],
                         'Height':[70],
                         'Weight':[150]})

result = model.predict(new_data)

print(result)

   PIQ  Brain  Height  Weight
0  132  85.78    62.5     127
1   96  86.54    68.0     135
2   84  90.49    66.3     134
                            OLS Regression Results
==============================================================================
Dep. Variable:                    PIQ   R-squared:                       0.370
Model:                            OLS   Adj. R-squared:                  0.329
Method:                 Least Squares   F-statistic:                     9.024
Date:                Wed, 26 Nov 2025   Prob (F-statistic):           8.25e-05
Time:                        17:23:44   Log-Likelihood:                -217.27
No. Observations:                  50   AIC:                             442.5
Df Residuals:                      46   BIC:                             450.2
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     74.5114     50.564      1.474      0.147     -27.269     176.292
Brain          2.3431      0.456      5.141      0.000       1.426       3.261
Height        -2.6444      1.064     -2.485      0.017      -4.786      -0.503
Weight         0.0406      0.167      0.243      0.809      -0.296       0.377
==============================================================================
Omnibus:                        8.608   Durbin-Watson:                   2.386
Prob(Omnibus):                  0.014   Jarque-Bera (JB):                2.629
Skew:                           0.041   Prob(JB):                        0.269
Kurtosis:                       1.880   Cond. No.                     3.48e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.48e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
0.37
0    106.38302
dtype: float64

In [ ]:
# import pandas as pd
# #df = pd.read_csv("design.csv")
# df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert_v2/main/part4/ch9/design.csv")
# print(df.head())
# cond1 = df['id']<=140
# cond2 = df['id']>140
# ## 실수 부분 나는 그냥 df['id'].iloc(:140)이렇게 했음
# train = df[cond1]
# test = df[cond2]

# print(train.shape , test.shape)

# #1. 
# # formula = 'design ~ c1+c2+c3+c4+c5'

# # from statsmodels.formula.api import ols

# # model = ols(formula, data = train).fit()

# # count = (model.pvalues[1:]<0.05).sum()
# # # 맨첫번째는 무조건 제외한다.
# # print(count)


# #2 피어슨 상관계수
# #corr 의 기본이 피어슨 상관계수임
# formula = 'design ~ c1+c2+c4'

# model = ols(formula , data = train).fit()

# train['pred_design'] = model.predict(train)

# result = train['design'].corr(train['pred_design'])

# print(result)


# # rmsc산출

# from sklearn.metrics import root_mean_squared_error

# pred = model.predict(test)

# result = root_mean_squared_error(pred, test['design'])

# print(result)



import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert_v2/main/part4/ch9/retention.csv")
df.head()

from statsmodels.formula.api import logit

formula = 'Churn ~ MonthlyCharges+ CustomerTenure+	HasPhoneService	+HasTechInsurance'

model = logit(formula, data =df).fit()

print(round(model.pvalues['MonthlyCharges'],3))


import numpy as np

#odds 비 np.exp(model.params[])
result = np.exp(model.params['HasPhoneService'])

print(round(result,3))

Optimization terminated successfully.
         Current function value: 0.582234
         Iterations 6
0.008
0.701

In [14]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch2/members.csv")
# print(df.head(3))
# df.sort_values('views', ascending = False , inplace = True)
# select_views = df['views'].iloc[:10].min()
# print(select_views)
# df.iloc[:10,-1] = select_views
# print(df.head())
# cond = df['age']>=80
# print(df[cond]['views'].mean())

df.sort_values('views' , ascending = False , inplace = True)
min_views = df['views'].iloc[:10].min()
print(min_views)
df.iloc[:10,-1] = min_views
print(df.head())
cond = df['age']>= 80
result = df[cond]['views'].mean()
print(result)

# df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch2/members.csv")

9690.0
       id   age city    f1  f2   f3    f4         f5  subscribed   views
5    id06  22.0   서울  57.0   0  vip  INTP  20.129444  2021-09-12  9690.0
56   id56  59.0   대구   NaN   1  vip  ESTJ  73.586397  2021-04-05  9690.0
83   id83  73.0   경기  50.0   1  vip  ENTP  80.138280  2021-09-26  9690.0
32   id32  25.0   부산  64.0   0  vip  ISFJ  13.049921  2021-05-24  9690.0
10  id100  47.0   경기  53.0   0  vip  ESFP  33.308999  2021-02-21  9690.0
5674.04347826087

In [25]:
import pandas as pd 
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch2/members.csv")
# line = int(len(df)*0.8)
# df = df.iloc[:line]
# print(df.head())
# # 표준 편차 는 std이당
# before_std = df['f1'].std()
# df.isnull().sum()
# f1_med = df['f1'].mean()
# df['f1'] = df['f1'].fillna(f1_med)
# after_std = df['f1'].std()
# print(before_std, after_std)
# result = abs(before_std - after_std)
# print(result)

line = int(len(df)*0.8)
df = df.iloc[:line]

before_std = df['f1'].std()
mean = df['f1'].mean()

df['f1'] = df['f1'].fillna(mean)

after_std = df['f1'].std()

reuslt = abs(before_std - after_std)

print(result)

3.5642356651913083

In [33]:
import pandas as pd
# df = pd.read_csv("members.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch2/members.csv")

print(df.head())

#age 컬럼의 이상치를 더하기 이상치 -> mean+- std *1.5
mean = df['age'].mean()

std = df['age'].std()

smaller = df['age']<mean-(std*1.5)
larger = df['age']>mean+(std*1.5)

result = df['age'][smaller].sum() + df['age'][larger].sum()
print(df.head())

print(result)

     id   age city    f1  f2    f3    f4         f5  subscribed   views
0  id01   2.0   서울   NaN   0  gold  ENFJ  91.297791  2021-07-16  6820.0
1  id02   9.0   서울  70.0   1   NaN  ENFJ  60.339826  2021-05-12  2534.0
2  id03  27.0   서울  61.0   1  gold  ISTJ  17.252986  2021-03-16  7312.0
3  id04  75.0   서울   NaN   2   NaN  INFP  52.667078  2021-07-21   493.0
4  id05  24.0   서울  85.0   2   NaN  ISFJ  29.269869  2021-03-07  1338.0
     id   age city    f1  f2    f3    f4         f5  subscribed   views
0  id01   2.0   서울   NaN   0  gold  ENFJ  91.297791  2021-07-16  6820.0
1  id02   9.0   서울  70.0   1   NaN  ENFJ  60.339826  2021-05-12  2534.0
2  id03  27.0   서울  61.0   1  gold  ISTJ  17.252986  2021-03-16  7312.0
3  id04  75.0   서울   NaN   2   NaN  INFP  52.667078  2021-07-21   493.0
4  id05  24.0   서울  85.0   2   NaN  ISFJ  29.269869  2021-03-07  1338.0
473.5

In [ ]:
# 데이터 불러오기
import pandas as pd
# X_test = pd.read_csv("X_test.csv")
# X_train = pd.read_csv("X_train.csv")
# y_train = pd.read_csv("y_train.csv")
X_test = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch2/X_test.csv")
X_train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch2/X_train.csv")
y_train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch2/y_train.csv")

df= pd.concat([X_train , y_train ['Reached.on.Time_Y.N']], axis =1)

# print(df.head() , df.info(), df.describe())


df = pd.get_dummies(df)
X_test = pd.get_dummies(X_train)

target = df.pop('Reached.on.Time_Y.N')


from sklearn.model_selection import train_test_split
x_train , x_val , y_train , y_val = train_test_split(df, target , test_size = 0.2 , random_state = 0)

print(x_train.shape , x_val.shape)

from sklearn.ensemble  import RandomForestClassifier

model = RandomForestClassifier(random_state = 0)

model.fit(x_train , y_train)

pred = model.predict_proba(x_val)
print(pred)

from sklearn.metrics import roc_auc_score
print(roc_auc_score(y_val,pred[:,1]))

# auc_roc_score 는 확률을 넣어야함 pred는 0일확률 1일 확률이 나옴 그래서 1열 부분을 출력하는거임

(7039, 20) (1760, 20)
[[0.   1.  ]
 [0.   1.  ]
 [0.54 0.46]
 ...
 [0.   1.  ]
 [0.65 0.35]
 [0.   1.  ]]
0.7551985244802145

In [ ]:
import pandas as pd
# df = pd.read_csv("members.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch3/members.csv")
#결측치 있는 행 제거 -> dropna
df.isnull().sum()
df = df.dropna()
line = len(df)*0.7
df = df.iloc[:int(line)]
result = df['f1'].quantile(.25)
print(result.astype(int))

57

In [68]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch3/year.csv', index_col='Unnamed: 0')

print(df.head())

mean = df.loc[2000].mean()

print(mean)

cond = df.loc[2000][0:] > mean

print(df.loc[2000][cond].sum())

        0    1    2    3    4    5    6    7    8    9  ...  190  191  192  \
1999  137   74  114  140   80  150   16  133  178  181  ...  124   94  118
2000  176   87   64  110  128   16    8    4  123   87  ...   59   22    3
2001  128  132  123  112  134  160  180   47  115  155  ...  160  111  116

      193  194  195  196  197  198  199
1999   12   50  191  137  174   56  128
2000  108   17  104  101  161  156   43
2001   75   48   51   81  101  194   73

[3 rows x 200 columns]
100.735
15224

In [ ]:
import pandas as pd
# df = pd.read_csv("members.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch2/members.csv")


#결측치가 가장 많은 컬럼 명


print(df.isnull().sum())

isnull = df.isnull().sum()

isnull.sort_values(ascending = False)

# 인덱스 명 - df.index[0]
print(isnull.index[0])

id             0
age            0
city           0
f1            31
f2             0
f3            28
f4             0
f5             0
subscribed     0
views          4
dtype: int64
id

In [ ]:
# 데이터 불러오기
import pandas as pd
# train = pd.read_csv("train.csv")
# test = pd.read_csv("test.csv")
train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch3/train.csv")
test = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch3/test.csv")

print(train.head())
# print(train.info())
# print(train.isnull().sum())

# print(train.describe(include = 'object'))

target = train.pop('TravelInsurance')

# train = pd.get_dummies(train)
# test = pd.get_dummies(test)


from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
# 자주틀리는 부분 - labelencoder = cols 설정 -> cols = train.select_dtypes(include = 'object').columns
cols = train.select_dtypes(include = 'object').columns

for col in cols:

    train[col] = le.fit_transform(train[col])
    test[col] = le.transform(test[col])


from sklearn.model_selection import train_test_split

x_train , x_val , y_train , y_val = train_test_split(train , target , test_size = 0.2 , random_state =0)

print(x_train.shape , x_val.shape)


from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(random_state =0)

model.fit(x_train ,y_train)

pred = model.predict_proba(x_val)

from sklearn.metrics import roc_auc_score

result = roc_auc_score(y_val , pred[:,1])

print(result)


pred = model.predict_proba(test)


result = pd.DataFrame({'pred':pred})

result.to_csv("result.csv", index = False)

# 0.8506578947368421
#0.8610380116959064

   Unnamed: 0  Age               Employment Type GraduateOrNot  AnnualIncome  \
0         888   28  Private Sector/Self Employed           Yes       1250000
1        1308   31  Private Sector/Self Employed           Yes       1250000
2         151   29  Private Sector/Self Employed           Yes       1200000
3         396   33             Government Sector           Yes        650000
4         135   28  Private Sector/Self Employed           Yes        800000

   FamilyMembers  ChronicDiseases FrequentFlyer EverTravelledAbroad  \
0              6                1            No                  No
1              7                1            No                  No
2              7                0            No                  No
3              6                1            No                  No
4              6                0            No                 Yes

   TravelInsurance
0                0
1                0
2                1
3                1
4                1
(1192, 9) (298, 9)
0.8610380116959064

In [101]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch2/members.csv")
#4.1


df.sort_values('age', ascending = False, inplace = True)
print(df.head())

one = df['age'].quantile(.25)
three = df['age'].quantile(.75)

print(one, three)

result = abs(three - one)

print(int(result))

      id    age city    f1  f2      f3    f4         f5  subscribed   views
37  id37  100.0   부산   NaN   0  silver  ESTP  33.308999  2021-07-08  4068.0
97  id97  100.0   경기   NaN   0    gold  INFP  67.886373  2021-03-18  6687.0
92  id92   97.0   경기  78.0   1    gold  INFP  97.381034  2021-05-08  9625.0
52  id52   97.0   대구  82.0   1    gold  ISFJ  90.496999  2021-05-20  8518.0
45  id45   97.0   대구  88.0   0    gold  ENFJ  13.049921  2021-06-21  8317.0
26.875 77.0
50

In [ ]:
import pandas as pd
# # df = pd.read_csv("members.csv")
# df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch4/data4-2.csv")
# # print(df.head())
# df['ratio'] = (df['loves']+df['wows'])/df['reactions']
# # print(df.head())
# cond1 = df['ratio']>0.4 
# cond2 = df['ratio']<0.5
# cond3 = df['type'] == 'video'
# df = df[cond1&cond2&cond3]
# print(df.head())
# # 개수 셀때 안되면 = len -> 길이를 구하면됨 sum은 숫자일때 합 boolean일때 개수 구함
# print(len(df))

        id   type  reactions  comments  shares  likes  loves  wows  hahas  \
3116  3117  video        255       926     181    142    108     0      5
4624  4625  video       1397       771     695    765    485   139      4
4776  4777  video        259       695     263    151    106     0      2
4793  4794  video        146       303     221     73     69     2      1
4812  4813  video        184       530     224    101     80     0      1

      sads  angrys     ratio
3116     0       0  0.423529
4624     1       3  0.446671
4776     0       0  0.409266
4793     0       1  0.486301
4812     1       1  0.434783
90

이거 복습 해야함 pd.to_datetime
dt.year 여기에 익숙해져야함

In [5]:
import pandas as pd
# df = pd.read_csv("data4-3.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch4/data4-3.csv")
# print(df.head())
# print(df.info())

# datetime 자료형으로 바꿔야함

#자료형 변환 pd.to_datetime(df[]) 이렇게 바꾼다.
#그리고 year month 도 dt.year dy.month이렇게 바꿔야함
# df['date_added'] = pd.to_datetime(df['date_added'])
# df['year'] = df['date_added'].dt.year
# df['month'] = df['date_added'].dt.month
# # print(df.head())
# cond1 = df['year'] == 2018
# cond2 = df['month'] == 1
# cond3 = df['country'] == 'United Kingdom'
# result = len(df[cond1&cond2&cond3])
# print(result)

print(df.head())
df['date_added'] =pd.to_datetime(df['date_added'])
df['year']= df['date_added'].dt.year
df['month'] = df['date_added'].dt.month

cond1 = df['year'] == 2018
cond2 = df['month'] == 1
cond3 = df['country'] == 'United Kingdom'

print(int(len(df[cond1&cond2&cond3])))

  show_id     type                  title         director  \
0      s1    Movie   Dick Johnson Is Dead  Kirsten Johnson
1      s2  TV Show          Blood & Water              NaN
2      s3  TV Show              Ganglands  Julien Leclercq
3      s4  TV Show  Jailbirds New Orleans              NaN
4      s5  TV Show           Kota Factory              NaN

                                                cast        country  \
0                                                NaN  United States
1  Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa
2  Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...            NaN
3                                                NaN            NaN
4  Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...          India

           date_added  release_year rating   duration  \
0  September 25, 2021          2020  PG-13     90 min
1  September 24, 2021          2021  TV-MA  2 Seasons
2  September 24, 2021          2021  TV-MA   1 Season
3  September 24, 2021          2021  TV-MA   1 Season
4  September 24, 2021          2021  TV-MA  2 Seasons

                                           listed_in
0                                      Documentaries
1    International TV Shows, TV Dramas, TV Mysteries
2  Crime TV Shows, International TV Shows, TV Act...
3                             Docuseries, Reality TV
4  International TV Shows, Romantic TV Shows, TV ...
6

In [135]:
# 데이터 불러오기
import pandas as pd

# train = pd.read_csv("train.csv")
# test = pd.read_csv("test.csv")
train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch4/train.csv")
test = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch4/test.csv")

# print(train.head())
print(train.info())

target = train.pop('Segmentation')

# train = pd.get_dummies(train)
# test = pd.get_dummies(test)

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

cols = train.select_dtypes(include = 'object').columns

for col in cols:
    train[col] = le.fit_transform(train[col])
    test[col] = le.fit_transform(test[col])



from sklearn.model_selection import train_test_split

x_train , x_val , y_train , y_val = train_test_split(train , target , test_size = 0.2 , random_state = 0)

from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(random_state= 0)

model.fit(x_train , y_train)

pred = model.predict(x_val)


from sklearn.metrics import f1_score

# 중요 average = 'macro' 이게 필요하다
print(f1_score(y_val , pred , average = 'macro'))

#0.5020137672414862
#0.5207983347962359

pred= model.predict(test)


result = pd.DataFrame({'ID':test['ID'],
                       'Segmentation':pred})

result.to_csv('result.csv', index= False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6665 entries, 0 to 6664
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               6665 non-null   int64
 1   Gender           6665 non-null   object
 2   Ever_Married     6665 non-null   object
 3   Age              6665 non-null   int64
 4   Graduated        6665 non-null   object
 5   Profession       6665 non-null   object
 6   Work_Experience  6665 non-null   float64
 7   Spending_Score   6665 non-null   object
 8   Family_Size      6665 non-null   float64
 9   Var_1            6665 non-null   object
 10  Segmentation     6665 non-null   int64
dtypes: float64(2), int64(3), object(6)
memory usage: 572.9+ KB
None
0.5207983347962359

In [30]:
import pandas as pd
# df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch5/data5-1.csv")
# print(df.head())
# cond1 = df['종량제봉투종류'] == '규격봉투'
# cond2 = df['종량제봉투용도'] == '음식물쓰레기'
# cond3 = df['2ℓ가격'] !=0
# df = df[cond1 & cond2 & cond3]
# mean = df['2ℓ가격'].mean()
# print(df.head())
# print(round(mean))
# df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch5/data5-2.csv")
# print(df.head())

# df['convert_height'] = df['Height']/100

# df['convert_height'] = df['convert_height']*df['convert_height']

# df['bmi'] = df['Weight']/df['convert_height']

# df.sort_values('bmi', ascending = False , inplace = True)

# print(df.head())

# cond1= (18.5 <= df['bmi'])& (df['bmi']< 23)

# cond2 = (23<=df['bmi'])&(df['bmi']<25)

# print(abs(len(df[cond1]) - len(df[cond2])))

# # 길이를 구할때는 sum 보다 len으로 하셈

df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch5/data5-3.csv")

df['순전입학생수'] =  df['1학년 전입학생수']- df['1학년 전출학생수'] - df['2학년 전출학생수'] + df['2학년 전입학생수'] + df['3학년 전입학생수'] - df['3학년 전출학생수']+ df['4학년 전입학생수'] - df['4학년 전출학생수']+ df['5학년 전입학생수'] - df['5학년 전출학생수']+ df['6학년 전입학생수'] - df['6학년 전출학생수']

print(df.head())

df.sort_values('순전입학생수' , ascending = False , inplace = True)

print(df.iloc[0,-2])

      시도교육청           지역교육청         지역   정보공시 학교코드              학교명  학교급코드  \
0  서울특별시교육청             교육부  서울특별시 서초구  S000003511    서울교육대학교부설초등학교      2
1  서울특별시교육청             교육부  서울특별시 종로구  S000003563  서울대학교사범대학부설초등학교      2
2  서울특별시교육청  서울특별시강남서초교육지원청  서울특별시 강남구  S010000738         서울개일초등학교      2
3  서울특별시교육청  서울특별시강남서초교육지원청  서울특별시 강남구  S010000741         서울구룡초등학교      2
4  서울특별시교육청  서울특별시강남서초교육지원청  서울특별시 강남구  S010000742         서울논현초등학교      2

  설립구분 제외여부 제외사유  1학년 전입학생수  ...  5학년 전입학생수  5학년 전출학생수  5학년 전체학생수  6학년 전입학생수  \
0   국립    N  NaN        5.0  ...        0.0        0.0      108.0        0.0
1   국립    N  NaN        4.0  ...        3.0        2.0      104.0        0.0
2   공립    N  NaN       13.0  ...       19.0        8.0      177.0       16.0
3   공립    N  NaN        2.0  ...       18.0        4.0      129.0       13.0
4   공립    N  NaN        1.0  ...        2.0       10.0       53.0        0.0

   6학년 전출학생수  6학년 전체 학생수  전입학생수(계)  전출학생수(계)  전체학생수(계)  순전입학생수
0        0.0       111.0       6.0       0.0     611.0     6.0
1        1.0       106.0      20.0      21.0     621.0    -1.0
2        5.0       152.0     118.0      50.0    1004.0    68.0
3        3.0       119.0      90.0      27.0     733.0    63.0
4        0.0        47.0       6.0      29.0     290.0   -23.0

[5 rows x 31 columns]
230.0

In [ ]:
# 데이터 불러오기
import pandas as pd
# train = pd.read_csv("train.csv")
# test = pd.read_csv("test.csv")
train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch5/train.csv")
test = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch5/test.csv")


print(train.head())
# print(df.info())
# print(train.isnull().sum())

target = train.pop('price')

train = pd.get_dummies(train)
test = pd.get_dummies(test)


from sklearn.model_selection import train_test_split
x_train , x_val, y_train , y_val = train_test_split(train , target , test_size = 0.2 , random_state = 0)

from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor(random_state = 0)

model.fit(x_train , y_train)

pred = model.predict(x_val)

from sklearn.metrics import root_mean_squared_error

print(root_mean_squared_error(y_val , pred))


pred = model.predict(test)

result = pd.DataFrame({'pred': pred})



result.to_csv('result.csv', index = False)


pd.read_csv('result.csv')

       model  year  price transmission  mileage fuelType  tax   mpg  \
0   EcoSport  2017  10298       Manual    25013   Petrol  150  53.3
1      Focus  2016  10491       Manual    30970   Diesel    0  74.3
2      S-MAX  2017  13498       Manual    60200   Diesel  150  56.5
3     Fiesta  2018  10600       Manual    27380   Petrol  145  56.5
4     Fiesta  2018  11000       Manual     7724   Petrol  145  65.7

   engineSize
0         1.0
1         1.5
2         2.0
3         1.0
4         1.0
1341.943732584459

      Unnamed: 0      pred
0              0  15586.88
1              1  15407.71
2              2  14912.47
3              3  18482.73
4              4   6168.01
...          ...       ...
1612        1612  10887.99
1613        1613  17320.61
1614        1614   9299.85
1615        1615  14523.67
1616        1616   4921.74

[1617 rows x 2 columns]

In [ ]:
import pandas as pd
# df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch6/data6-1-1.csv")
# # print(df.head())
# # df['출동시간'] = pd.to_datetime(df['출동시간'])
# # df['도착시간'] = pd.to_datetime(df['도착시간'])
# # df['시간차이'] = (df['도착시간'] - df['출동시간']).dt.total_seconds()/60
# # avg_diff = df.groupby('소방서')['시간차이'].mean()
# # idx = avg_diff.idxmax()
# df['출동시간'] = pd.to_datetime(df['출동시간'])
# df['도착시간'] = pd.to_datetime(df['도착시간'])
# df['시간차이']= (df['도착시간']-df['출동시간']).dt.total_seconds()/60
# avg_diff = df.groupby('소방서')['시간차이'].mean()
# max = avg_diff.idxmax()
# result = avg_diff[max]
# print(round(result))


# df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch6/data6-1-2.csv")

# print(df.head())

# df['전교생'] = df['1학년']+ df['2학년'] + df['3학년']+ df['4학년']+ df['5학년']+ df['6학년']

# df['비율'] = df['전교생']/df['교사수']

# df = df.sort_values( '비율', ascending = False)

# print(df.head())

# print(df.iloc[0,1])

# df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch6/data6-1-3.csv")

# df['총범죄건수'] = df['강력범죄'] + df['절도범죄'] + df['폭력범죄'] + df['지능범죄']+ df['풍속범죄'] + df['교통범죄']


# # 몰랐던 부분 -  연도를 앞에 4글짜로 슬라이싱
# df['연도'] = df['날짜'].str[:4]


# result = df['총범죄건수'].groupby(df['연도']).sum()

# print(round(result.max()/12))


df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch6/data6-1-1.csv")


print(df.head())

df['출동시간'] = pd.to_datetime(df['출동시간'])
df['도착시간'] = pd.to_datetime(df['도착시간'])
df['시간차이'] = (df['도착시간'] - df['출동시간']).dt.total_seconds()/60

avg_diff = df.groupby('소방서')['시간차이'].mean()
max = avg_diff.idxmax()
result = avg_diff[max]
print(round(result))

avg = df.groupby('소방서')['시간차이'].mean()
max = avg.idxmax()
result = avg[max]
print(round(result))


max2 = avg.sort_values(ascending =False)

    소방서                 출동시간                 도착시간
0  소방서1  2023-09-16 06:12:29  2023-09-16 07:51:55
1  소방서5  2023-09-19 06:11:41  2023-09-19 08:08:36
2  소방서1  2023-09-14 06:12:00  2023-09-14 07:24:21
3  소방서6  2023-09-20 06:12:24  2023-09-20 06:30:45
4  소방서9  2023-09-15 06:11:50  2023-09-15 06:44:00
81
81
81

C:\Users\김금영\AppData\Local\Temp\ipykernel_3528\3572351450.py:69: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(round(max2[0]))

In [79]:
# 데이터 불러오기
import pandas as pd
# train = pd.read_csv("energy_train.csv")
# test = pd.read_csv("energy_test.csv")
train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch6/energy_train.csv")
test = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch6/energy_test.csv")


# print(train.head())

target = train.pop('Heat_Load')

train = pd.get_dummies(train)
test = pd.get_dummies(test)

from sklearn.model_selection import train_test_split
x_train , x_val , y_train ,y_val = train_test_split(train , target , test_size = 0.2 , random_state = 0)


from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(random_state = 0)
model.fit(x_train , y_train)


pred = model.predict(x_val)
from sklearn.metrics import f1_score

print(f1_score(y_val , pred , average = 'macro'))


pred = model.predict(test)


result = pd.DataFrame({'pred':pred})

result.to_csv('result.csv',index = False)

print(pd.read_csv('result.csv'))

0.9277616846430405
          pred
0          Low
1         High
2         High
3          Low
4          Low
..         ...
226   Very Low
227     Medium
228   Very Low
229        Low
230  Very High

[231 rows x 1 columns]

In [93]:
import pandas as pd


df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch6/data6-3-2.csv")


from statsmodels.formula.api import ols
print(df.head())

formula = 'temperature~ solar + wind + o3'


model = ols(formula , data = df).fit()

print(model.params['o3'])
print(model.pvalues['wind'])
new_data = pd.DataFrame({'solar':[100],
                         'wind':[5],
                         'o3':[30]})

pred = model.predict(new_data)

print(pred)

    solar   wind     o3  temperature
0   89.14   6.28  33.52         23.0
1  109.97   1.04  27.01         20.7
2  102.83   6.42  41.00         20.5
3   84.94  10.20  33.44         22.2
4   94.21   4.95  29.97         21.4
0.07493854378136597
0.7797177202071699
0    21.56163
dtype: float64

In [42]:
import pandas as pd
# df = pd.read_csv("data6-3-2.csv")
# import pandas as pd
df = pd.DataFrame({
    "항암약":[4,4,3,4,1,4,1,4,1,4,4,2,1,4,2,3,2,4,4,4]
    })
# count = sum(df['항암약'] == 4)
# total = len(df['항암약'])
# ratio = count/total
# print(ratio)
from scipy.stats import chisquare
# prob = [0.1 , 0.05, 0.15, 0.7]
# exp_prob = [0.1*20 , 0.05*20, 0.15*20, 0.7*20]
# obs_prob = df['항암약'].value_counts().sort_index().tolist()
# print(chisquare(f_obs = obs_prob , f_exp = exp_prob))
# 카이제곱 - 관측 도수 와 기대도수 (f_obs , f_exp)를 넣어야한다.
exp_prob = [0.1*20 , 0.05*20, 0.15*20, 0.7*20]
obs_prob = df['항암약'].value_counts().sort_index().tolist()
#.value_counts().sort_index().tolist()

print(chisquare(f_obs = obs_prob , f_exp = exp_prob))



df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch6/data6-3-2.csv")

from statsmodels.formula.api import ols
print(df.head())
formula = 'temperature ~ solar + wind + o3'

model = ols(formula, data = df).fit()

print(model.params['o3'])


print(model.pvalues['wind'])

new_data = pd.DataFrame({'solar':[100], 'wind':[0.5], 'o3':[30]})

result = model.predict(new_data)

print(result[0])

Power_divergenceResult(statistic=6.976190476190476, pvalue=0.07266054733847571)
    solar   wind     o3  temperature
0   89.14   6.28  33.52         23.0
1  109.97   1.04  27.01         20.7
2  102.83   6.42  41.00         20.5
3   84.94  10.20  33.44         22.2
4   94.21   4.95  29.97         21.4
0.07493854378136597
0.7797177202071699
21.675129758635755

In [54]:
# 데이터 불러오기
import pandas as pd
# train = pd.read_csv("mart_train.csv")
# test = pd.read_csv("mart_test.csv")
train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch7/mart_train.csv")
test = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch7/mart_test.csv")

# print(train.head())
# print(train.info())
print(train['total'].describe())

target = train.pop('total')

train = pd.get_dummies(train)
test = pd.get_dummies(test)

from sklearn.preprocessing import LabelEncoder

# cols = train.select_dtypes(include='object')

# for col in cols:
    
#     encoder = LabelEncoder()
#     train[col] = encoder.fit_transform(train[col])
#     test[col] = encoder.transform(test[col])    


from sklearn.model_selection import train_test_split
x_train , x_val , y_train , y_val = train_test_split(train, target, test_size = 0.2 , random_state = 0)

from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor(random_state = 0)

model.fit(x_train ,y_train)

pred = model.predict(x_val)

from sklearn.metrics import root_mean_squared_error

print(root_mean_squared_error(y_val , pred))
#rmse 는 0에 가까울 수록 좋은 모델

pred = model.predict(test)

result = pd.DataFrame({'pred':pred})

result.to_csv('result.csv', index = False)

pd.read_csv('result.csv')

print(train.shape, test.shape)

count    7.000000e+02
mean     4.850780e+05
std      3.643907e+05
min      1.904175e+04
25%      2.001195e+05
50%      3.818745e+05
75%      7.061276e+05
max      1.563975e+06
Name: total, dtype: float64
385935.56337360526
(700, 30) (300, 30)

In [ ]:
# import pandas as pd
# # df = pd.read_csv("clam.csv")
# df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch7/clam.csv")

# from statsmodels.formula.api import logit
# import numpy as np

# train = df.iloc[:210]
# test = df.iloc[210:]

# print(train.shape, test.shape)

# # print(df.head(1))

# # formula = 'gender ~ weight'

# # model = logit(formula , data = train).fit()

# # odds_ratio = np.exp(model.params['weight']) 
# # print(odds_ratio)

# formula = 'gender ~ age + length + diameter + height + weight '



# # 잔차이탈도 - 모델의 적합도 - 로그우도 llf 값에 -2 곱하면 잔차이탈도임



# from sklearn.metrics import accuracy_score

# target = test.pop('gender')


# model = logit('gender ~ weight', data = train).fit()

# pred = model.predict(test)

# pred = (pred>0.5).astype(int)

# ## 여기 pred int로 반환시키는거 주요 -> (pred>0.5).astype(int)

# accracy = accuracy_score(target , pred)

# error = 1 - accracy

# print(error)



df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch7/system_cpu.csv")


#1
print(df.corr())

from statsmodels.formula.api import ols 
# 0.882 feature3
import numpy as np


#2
cond1 = df['CPU']<100
df = df[cond1]
formula = 'ERP ~ Feature1 +Feature2 +Feature3+CPU'

model = ols(formula , data = df).fit()
print(model.summary())

#0.755
#3 Feature1

               ERP  Feature1  Feature2  Feature3       CPU
ERP       1.000000 -0.053848  0.092432  0.882194  0.092455
Feature1 -0.053848  1.000000 -0.020095 -0.015767  0.023664
Feature2  0.092432 -0.020095  1.000000  0.118877  0.130492
Feature3  0.882194 -0.015767  0.118877  1.000000  0.137120
CPU       0.092455  0.023664  0.130492  0.137120  1.000000
                            OLS Regression Results
==============================================================================
Dep. Variable:                    ERP   R-squared:                       0.755
Model:                            OLS   Adj. R-squared:                  0.736
Method:                 Least Squares   F-statistic:                     39.30
Date:                Fri, 28 Nov 2025   Prob (F-statistic):           5.36e-15
Time:                        14:46:25   Log-Likelihood:                -260.40
No. Observations:                  56   AIC:                             530.8
Df Residuals:                      51   BIC:                             540.9
Df Model:                           4
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     51.4133     19.112      2.690      0.010      13.045      89.782
Feature1      -0.0242      0.059     -0.409      0.684      -0.143       0.094
Feature2       0.0602      0.106      0.569      0.572      -0.152       0.273
Feature3       1.4126      0.113     12.458      0.000       1.185       1.640
CPU           -0.4651      0.234     -1.985      0.053      -0.936       0.005
==============================================================================
Omnibus:                        3.758   Durbin-Watson:                   1.762
Prob(Omnibus):                  0.153   Jarque-Bera (JB):                2.757
Skew:                           0.436   Prob(JB):                        0.252
Kurtosis:                       3.648   Cond. No.                         780.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [96]:
import pandas as pd
# train = pd.read_csv("churn_train.csv")
# test = pd.read_csv("churn_test.csv")
train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch8/churn_train.csv")
test = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch8/churn_test.csv")


# print(train.info())
# print(train.shape , test.shape)

print(train.isnull().sum())

target = train.pop('TotalCharges')

from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()


train = train.drop('customerID', axis = 1)
test = test.drop('customerID', axis = 1)

cols = train.select_dtypes(include = 'object')

for col in cols :
    encoder = LabelEncoder()
    train[col] = encoder.fit_transform(train[col])
    test[col] = encoder.transform(test[col])


# train = pd.get_dummies(train)
# test = pd.get_dummies(test)

from sklearn.model_selection import train_test_split

x_train , x_val , y_train , y_val = train_test_split(train , target , test_size = 0.2 , random_state = 0)

from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(random_state = 0)

model.fit(x_train ,y_train)

pred = model.predict(x_val)

from sklearn.metrics import mean_absolute_error

print(mean_absolute_error(y_val , pred))

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
TotalCharges        0
dtype: int64
951.0960435538027

In [4]:
import pandas as pd
# # df = pd.read_csv("churn.csv")
# df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch8/churn.csv")

#1
from statsmodels.formula.api import logit


# formula = 'Churn ~ AccountWeeks + ContractRenewal + DataPlan + DataUsage + CustServCalls + DayMins + DayCalls + MonthlyCharge + OverageFee + RoamMins'

# model = logit(formula, data = df).fit()

# # print(model.summary())

# print( model.pvalues)

# # 1번 정답  8개

# #2번
# import numpy as np

# formula = 'Churn ~ DataUsage+ DayMins'

# model = logit(formula , data = df).fit()

# print(model.summary())

# print(sum(model.params))

# # 3번

# odds_ratio = np.exp(model.params['DataUsage']*5)

# print(round(odds_ratio,3))
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch8/piq.csv")

#1번
from statsmodels.formula.api import ols
formula = 'PIQ ~ Brain + Height + Weight'

model = ols(formula , data = df).fit()

print(model.summary())

#brain

#2번 : 0.370

print(round(model.rsquared,2))


#3번

new_data = pd.DataFrame({'Brain':[90], 'Height': [70], 'Weight':[150]})

pred = model.predict(new_data)

print(round(pred,3))

                            OLS Regression Results
==============================================================================
Dep. Variable:                    PIQ   R-squared:                       0.370
Model:                            OLS   Adj. R-squared:                  0.329
Method:                 Least Squares   F-statistic:                     9.024
Date:                Fri, 28 Nov 2025   Prob (F-statistic):           8.25e-05
Time:                        15:37:17   Log-Likelihood:                -217.27
No. Observations:                  50   AIC:                             442.5
Df Residuals:                      46   BIC:                             450.2
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     74.5114     50.564      1.474      0.147     -27.269     176.292
Brain          2.3431      0.456      5.141      0.000       1.426       3.261
Height        -2.6444      1.064     -2.485      0.017      -4.786      -0.503
Weight         0.0406      0.167      0.243      0.809      -0.296       0.377
==============================================================================
Omnibus:                        8.608   Durbin-Watson:                   2.386
Prob(Omnibus):                  0.014   Jarque-Bera (JB):                2.629
Skew:                           0.041   Prob(JB):                        0.269
Kurtosis:                       1.880   Cond. No.                     3.48e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.48e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
0.37
0    106.383
dtype: float64

In [9]:
import pandas as pd
train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert_v2/main/part4/ch9/farm_train.csv")
test = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert_v2/main/part4/ch9/farm_test.csv")

# print(train.shape , test.shape)
# # print(train.info())
# train.isnull().sum()

target = train.pop('농약검출여부')

train = pd.get_dummies(train)
test = pd.get_dummies(test)

from sklearn.model_selection import train_test_split

x_train , x_val , y_train , y_val = train_test_split(train , target , test_size = 0.2 , random_state = 0)

from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(random_state = 0)

model.fit(x_train , y_train)

pred = model.predict(x_val)

from sklearn.metrics import f1_score

print(f1_score(y_val , pred , average = 'macro'))

pred = model.predict(test)

result = pd.DataFrame({'pred':pred})

result.to_csv('result.csv', index = False)

pd.read_csv('result.csv')

0.8532014300116062

     pred
0       2
1       0
2       0
3       2
4       0
..    ...
995     2
996     2
997     2
998     2
999     0

[1000 rows x 1 columns]

In [ ]:
import pandas as pd
# df = pd.read_csv("design.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert_v2/main/part4/ch9/design.csv")


# df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert_v2/main/part4/ch9/retention.csv")
#print(df.head(1))

from statsmodels.formula.api import ols

train = df.iloc[:140]
test = df.iloc[140:]

# formula = 'design ~ c1+c2+c3+c4+c5'

# model = ols(formula , data = train).fit()
# print(model.pvalues<0.05)

# 3개



# formula = 'design ~ c1 + c2 + c4'

# model = ols(formula , data = train).fit()

# train['pred_design'] = model.predict(train)

# result = train['design'].corr(train['pred_design'])


# print(round(result,3))

# target = test.pop('design')


# pred = model.predict(test)

# from sklearn.metrics import root_mean_squared_error

# result = root_mean_squared_error(target, pred)
# print(result)



df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert_v2/main/part4/ch9/retention.csv")
print(df.head(1))

from statsmodels.formula.api import logit

formula = 'Churn ~ MonthlyCharges + CustomerTenure + HasPhoneService  + HasTechInsurance'

model = logit(formula, data = df).fit()

print(model.summary())
#0.008


print(model.pvalues)

import numpy as np

result = np.exp(model.params['HasPhoneService'])

print(round(result, 3))

#3

pred = model.predict(df)
# sum은 boolean일 때사용하자
sum(pred>0.3)

   CustomerID  MonthlyCharges  CustomerTenure  HasPhoneService  \
0           1       77.450712              47                1

   HasTechInsurance  Churn
0                 1      1
Optimization terminated successfully.
         Current function value: 0.582234
         Iterations 6
                           Logit Regression Results
==============================================================================
Dep. Variable:                  Churn   No. Observations:                   80
Model:                          Logit   Df Residuals:                       75
Method:                           MLE   Df Model:                            4
Date:                Fri, 28 Nov 2025   Pseudo R-squ.:                  0.1585
Time:                        16:07:46   Log-Likelihood:                -46.579
converged:                       True   LL-Null:                       -55.352
Covariance Type:            nonrobust   LLR p-value:                  0.001513
====================================================================================
                       coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------
Intercept           -4.4731      1.437     -3.114      0.002      -7.289      -1.657
MonthlyCharges       0.0503      0.019      2.640      0.008       0.013       0.088
CustomerTenure       0.0428      0.014      3.016      0.003       0.015       0.071
HasPhoneService     -0.3558      0.525     -0.677      0.498      -1.386       0.674
HasTechInsurance    -0.4868      0.518     -0.940      0.347      -1.502       0.529
====================================================================================
Intercept           0.001847
MonthlyCharges      0.008293
CustomerTenure      0.002562
HasPhoneService     0.498213
HasTechInsurance    0.347465
dtype: float64
0.701

65

In [ ]:
# 출력을 원할 경우 print() 함수 활용
# 예시) print(df.head())

# getcwd(), chdir() 등 작업 폴더 설정 불필요
# 파일 경로 상 내부 드라이브 경로(C: 등) 접근 불가

import pandas as pd

df = pd.read_csv("data/employee_performance.csv")

# 사용자 코딩

mean = df['고객만족도'].mean()

df = df['고객만족도'].fillna(mean)

df = df.dropna(subset = ['근속연수'])

print(df['고객만족도'].quantile(.75))

cond1 = df.groupby('부서')['연봉'].mean()

print(cond[1])





# 해당 화면에서는 제출하지 않으며, 문제 풀이 후 답안제출에서 결괏값 제출

In [ ]:
# 출력을 원하실 경우 print() 함수 활용
# 예시) print(df.head())

# getcwd(), chdir() 등 작업 폴더 설정 불필요
# 파일 경로 상 내부 드라이브 경로(C: 등) 접근 불가

import pandas as pd

train = pd.read_csv("data/customer_train.csv")
test = pd.read_csv("data/customer_test.csv")

# 사용자 코딩

# 답안 제출 참고
# 아래 코드는 예시이며 변수명 등 개인별로 변경하여 활용
# pd.DataFrame변수.to_csv("result.csv", index=False)

In [45]:
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert_v2/main/part4/ch9/loan.csv")

df['총대출액'] = df['신용대출']+ df['담보대출']

cond1 = df.groupby(['지역코드', '성별'])['총대출액'].sum().unstack()

print(cond1)

cond1['차이'] = abs(cond1[1]-cond1[2])

print(cond1['차이'].idxmax())

성별                 1         2
지역코드
4100000000  22891981  18339609
4100000001  34197683  17595557
4100000002  13119017  21827691
4100000003  16549091  54654134
4100000004  26831399  56145359
...              ...       ...
4100000587   9050332  19445103
4100000588  47396699  36281031
4100000589  28256320  17797635
4100000590  16813363  23655928
4100000591  20674327  12204772

[592 rows x 2 columns]
4100000278

In [93]:
# 방법2
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert_v2/main/part4/ch9/crime.csv")
# print(df.head(3))
# # 1. 데이터를 길게 변환
# df_long = pd.melt(df, id_vars = ["연도", "구분"], var_name = "범죄유형" , value_name = "건수")
# print(df_long)
# # 2. 피벗(pivot)하여 발생건수와 검거건수를 한 행에 모으기:
# df_pivot = df_long.pivot_table(index = ["연도", "범죄유형"], columns = "구분" , values = "건수").reset_index()
# # 3. 검거율 계산
# df_pivot["검거율"] = df_pivot["검거건수"] / df_pivot["발생건수"]
# # 4. 각 연도별로 검거율이 가장 높은 범죄유형 찾기
# listbox = df_pivot.groupby("연도")["검거율"].idxmax()
# max_crime = df_pivot.loc[listbox]
# print(listbox , max_crime)
# # 5. 각 연도별 최고 검거율 범죄유형의 검거건수를 모두 합산하기
# result = max_crime["검거건수"].sum()
# result

df_long = pd.melt(df, id_vars = ['연도' , '구분'] 
                  , var_name = '범죄유형' ,
                    value_name = '건수')

print(df_long.head(3))

df_pivot = df_long.pivot_table(index = ['연도' , '범죄유형'],
                               columns = '구분',
                               values = '건수')


print(df_pivot.head(3))

df_pivot['검거율'] = df_pivot['검거건수']/df_pivot['발생건수']

list = df_pivot.groupby('연도')['검거율'].idxmax()

print(list)

max_crime = df_pivot.loc[list]
print(max_crime)

result = max_crime['검거건수'].sum()

print(result)

     연도    구분  범죄유형   건수
0  2014  발생건수  강력범죄  800
1  2014  검거건수  강력범죄  500
2  2015  발생건수  강력범죄  900
구분          검거건수    발생건수
연도   범죄유형
2014 강력범죄  500.0   800.0
     교통범죄  550.0   900.0
     기타범죄  600.0  1000.0
연도
2014    (2014, 특별경제범죄)
2015      (2015, 절도범죄)
2016      (2016, 폭력범죄)
2017      (2017, 마약범죄)
2018      (2018, 강력범죄)
2019      (2019, 보건범죄)
2020      (2020, 지능범죄)
Name: 검거율, dtype: object
구분             검거건수    발생건수       검거율
연도   범죄유형
2014 특별경제범죄   961.0  1034.0  0.929400
2015 절도범죄     713.0   768.0  0.928385
2016 폭력범죄     812.0   880.0  0.922727
2017 마약범죄    1300.0  1400.0  0.928571
2018 강력범죄    1350.0  1450.0  0.931034
2019 보건범죄    1300.0  1400.0  0.928571
2020 지능범죄    1363.0  1500.0  0.908667
7799.0

In [104]:
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert_v2/main/part4/ch9/hr.csv")

df['만족도'] = df['만족도'].fillna(df['만족도'].mean())
cond_1= df.groupby(['부서' , '성과등급'])['근속연수'].transform('mean')
df['근속연수'] = df['근속연수'].fillna(cond_1)



print(df.head(3))


df['연봉근속'] = df['연봉']/df['근속연수']
df['연봉만족'] = df['연봉']/df['만족도']

cond1 = df.nlargest(3,'연봉근속')
cond2 = df.nlargest(2, '연봉만족')

result1 = cond1.iloc[-1]['근속연수']
result2 = cond2.iloc[-1]['교육참가횟수']

print(result1, result2)

print(round(result1+result2))

    사원번호         부서 성과등급        연봉  근속연수  교육참가횟수  만족도
0  E0001  Marketing    B  73200000  14.0       5  6.0
1  E0002         IR    A  95100000   3.0       4  9.0
2  E0003    Manager    B  44700000   5.0       2  8.0
1.0 6
7

In [87]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch8/chem.csv")

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

df['co_scaled'] = scaler.fit_transform(df[['co']])
df['nmhc_scaler'] = scaler.fit_transform(df[['nmhc']])

co_std = df['co_scaled'].std()
nmhc_std = df['nmhc_scaler'].std()

print(co_std , nmhc_std)


print(round(co_std - nmhc_std , 3))

0.2856516497116944 0.3030617020578397
-0.017

In [1]:
import pandas as pd
# df = pd.read_csv("members.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch2/members.csv")


line = int(len(df) * 0.8)

df = df.iloc[:line]

before_std = df['f1'].std()


median = df['f1'].quantile(0.5)

df['f1'] = df['f1'].fillna(median)

after_std = df['f1'].std()

result = abs(before_std - after_std)

print(round(result, 2))

3.56

In [8]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch3/year.csv', index_col='Unnamed: 0')

print(df.head(2))

mean = df.loc[2000].mean()

print(mean)

print(sum(df.loc[2000]>mean))

        0   1    2    3    4    5   6    7    8    9  ...  190  191  192  193  \
1999  137  74  114  140   80  150  16  133  178  181  ...  124   94  118   12
2000  176  87   64  110  128   16   8    4  123   87  ...   59   22    3  108

      194  195  196  197  198  199
1999   50  191  137  174   56  128
2000   17  104  101  161  156   43

[2 rows x 200 columns]
100.735
100

In [11]:
import pandas as pd
# df = pd.read_csv("members.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch3/members.csv")

print(df.isnull().sum())

cond = df.isnull().sum()

print(cond.idxmax())

id             0
age            0
city           0
f1            31
f2             0
f3            28
f4             0
f5             0
subscribed     0
views          4
dtype: int64
f1

In [19]:
# 방법1
import pandas as pd
# df = pd.read_csv("data4-3.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch4/data4-3.csv")


df['date_added'] = pd.to_datetime(df['date_added'])
df['year'] = df['date_added'].dt.year
df['month'] = df['date_added'].dt.month

cond1 = df['year'] == 2018
cond2 = df['month'] == 1
cond3 = df['country'] == 'United Kingdom'


print(len(df[cond1 & cond2 & cond3]))

6

In [33]:
# df = pd.read_csv("data6-1-1.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch6/data6-1-1.csv")

df['출동시간'] = pd.to_datetime(df['출동시간'])
df['도착시간'] = pd.to_datetime(df['도착시간'])

df['시간차이'] = (df['도착시간'] - df['출동시간']).dt.total_seconds()/60


cond1 = df.groupby('소방서')['시간차이'].mean()

cond1 = cond1.sort_values(ascending = False)

print(cond1)

print(round(cond1.max()))

소방서
소방서9     80.658889
소방서5     61.250000
소방서2     60.228571
소방서7     56.670370
소방서1     54.952381
소방서4     49.136667
소방서3     43.490741
소방서8     42.693750
소방서10    42.365000
소방서6     41.764583
Name: 시간차이, dtype: float64
81

In [41]:
# 데이터 불러오기
import pandas as pd
train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch6/energy_train.csv")
test = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch6/energy_test.csv")

'''
 0   Compac       537 non-null    float64
 1   Surf_Area    537 non-null    float64
 2   Wall_Area    537 non-null    float64
 3   Roof         537 non-null    object 
 4   Height       537 non-null    object 
 5   Orient       537 non-null    object 
 6   Glaze_Area   537 non-null    float64
 7   Glaze_Distr  537 non-null    int64  
 8   Cool_Load    537 non-null    float64
 9   Heat_Load    537 non-null    object 
'''

target = train.pop('Heat_Load')

combined = pd.concat([train , test])
combined = pd.get_dummies(combined)
line = len(train)


train = combined[:line]
test = combined[line:]

from sklearn.model_selection import train_test_split
x_train, x_val , y_train , y_val = train_test_split(train , target , test_size = 0.2 , random_state = 0)

from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(random_state = 0)
model.fit(x_train , y_train)
pred = model.predict(x_val)

from sklearn.metrics  import f1_score
print(f1_score(y_val , pred , average = 'macro'))
pred = model.predict(test)
result = pd.DataFrame({'pred': pred})

result.to_csv('resul.csv', index = False)

print(pd.read_csv('result.csv'))

0.9277616846430405
     pred
0       2
1       0
2       0
3       2
4       0
..    ...
995     2
996     2
997     2
998     2
999     0

[1000 rows x 1 columns]

In [ ]:
import pandas as pd
from scipy.stats import chisquare

df = pd.DataFrame({"항암약":[4,4,3,4,1,4,1,4,1,4,4,2,1,4,2,3,2,4,4,4]})
# 관측도수
obs = df['항암약'].value_counts().sort_index().to_list()
# 기대도수
total = len(df)
exp = [0.1*total, 0.05*total, 0.15*total, 0.7*total]
print("Observed:", obs)
print("Expected:", exp)
print(chisquare(f_obs = obs , f_exp = exp))

Observed: [4, 3, 2, 11]
Expected: [2.0, 1.0, 3.0, 14.0]
Power_divergenceResult(statistic=6.976190476190476, pvalue=0.07266054733847571)

In [ ]:
import pandas as pd
# df = pd.read_csv("student_assessment.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch7/student_assessment.csv")

df = df.dropna()

id = df['id_assessment'].value_counts().idxmax()
cond = df['id_assessment'] == id
df = df[cond]

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df['score'] = scaler.fit_transform(df[['score']])

print(df['score'].max())

2.183422032552496

:

In [ ]:
import pandas as pd
# df = pd.read_csv("data6-3-2.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch6/data6-3-2.csv")
print(df.head(3))